name: Restless Productions
favicon: null
layout_spectrum: 0.58392
typography_spectrum: 0.87289
title: Restless Productions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#582341'
    - '#a80015'
    - '#787194'
    - '#5d57a5'
    - '#b22335'
  brandStrength: 0.3212011728901416
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.33343776129186153
purpose: []
